moscowracing/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('racing.urls')),
    path('users/', include('users.urls', namespace="users")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

handler404 = "moscowracing.views.page_not_found_view"

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views  # . means import from current module
from .views import LoginUser

app_name = "users"

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']
        labels = {
            'username': 'Логин: ',
            'password': 'Пароль: '
        }
        error_messages = {
            'username': {'required': 'Введите логин!'},
            'password': {'required': 'Введите пароль!'}
        }


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин: ',
                               error_messages={'required': 'Введите логин!'})
    password = forms.CharField(label='Пароль: ', widget=forms.PasswordInput(attrs={'class': 'form-input'}),
                               error_messages={'required': 'Введите пароль!'})
    password2 = forms.CharField(label='Повтор пароля: ', widget=forms.PasswordInput(attrs={'class': 'form-input'}),
                                error_messages={'required': 'Повторите пароль!'})

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
        labels = {
            'email': 'Почта: ',
            'first_name': 'Имя: ',
            'last_name': 'Фамилия: '
        }
        error_messages = {
            'username': {'required': 'Введите логин!'},
            'email': {'required': 'Введите email!'},
            'password': {'required': 'Введите пароль!'},
            'password2': {'required': 'Повторите пароль!'}
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Пароли не совпадают!")
        return cd['password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if email and get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Аккаунт с таким Email уже существует!")
        return email

users/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import render

from .forms import RegisterUserForm, LoginUserForm

menu = {
    "Трасса": "/track",
    "Автомобили": "/cars",
    'Аренда': '/rent',
}


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация', 'menu': menu}

    # def get_success_url(self):
    #     return reverse_lazy('track')


def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'users/register_done.html', context={'title': 'Сообщение', 'menu': menu})
    else:
        form = RegisterUserForm()
    data = {
        'title': 'Регистрация',
        'menu': menu,
        'form': form
    }
    return render(request, 'users/register.html', context=data)

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/users.css' %}">
{% endblock %}


{% block content %}

<div class="form-container">
    <form novalidate method="post">
        <h1>Авторизация</h1>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p id="{{ f.id_for_label }}"><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><a href="{% url 'users:register' %}">Нет аккаунта? Регистрация</a></p>
        <p><button type="submit">Войти</button></p>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/users.css' %}">
{% endblock %}


{% block content %}

<div class="form-container">
    <form novalidate method="post">
        <h1>Регистрация</h1>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p id="{{ f.id_for_label }}"><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><a href="{% url 'users:login' %}">Есть аккаунт? Войти</a></p>
        <p><button type="submit">Зарегистрироваться</button></p>
    </form>
</div>

{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/users.css' %}">
{% endblock %}


{% block content %}

<div class="form-container">
    <h3>Вы успешно зарегистрировались!!! Теперь вы можете авторизоваться по <a href="{% url 'users:login' %}">ссылке</a>!</h3>
</div>

{% endblock %}