moscowracing/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('racing.urls')),
    path('users/', include('users.urls', namespace="users")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

handler404 = "moscowracing.views.page_not_found_view"

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views  # . means import from current module
from .views import LoginUser

app_name = "users"

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block title %} {% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul class="menu">
                {% for key, value in menu.items %}
                    <li><a href='{{value}}'>{{ key }}</a></li>
                {% endfor %}
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <li class="last">{{ user.username }} | <button type="submit">Выйти</button></li>
                </form>
                {% else %}
                    <li class="last"><a href="{% url 'users:login' %}">Войти</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %} {% endblock %}
</body>
</html>